### GENERAL SETTINGS ###

# Site settings
title: 流白
description: ""
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://truenoda.github.io"
excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown
#permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: weibo
    url: http://weibo.com/1882819105   
  - title: twitter
    url: https://twitter.com/SteveJobsDA
  - title: flickr
    url: https://www.flickr.com/photos/108593526@N08/
  - title: facebook
    url: http://www.zhihu.com/people/liu-bai-27-78
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page. mailto:mytharcher@gmail.com
address:
  - lines: 
    - 
email: truenotrueno@sina.com



### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
# Clients information. Shown on Home and About pages.
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "        Copyright@2014 "

# Testimonial content. Shown on Home and About page. 
testimonial:
    #message: "流白啊"
    author: 岁月你别催   该来的我不推  该还的还该给的我给
    position: 岁月你别催   走远的我不追  我不过是想弄清原委
